# Configuração do SCRAP_SAM
project:
  name: "SCRAP_SAM"
  version: "1.0.0"
  description: "Sistema de scraping e análise de dados do SAM da Itaipu"

# Configurações de scraping
scraping:
  timeout: 30
  max_retries: 3
  headless: false
  wait_time: 10
  download_dir: "downloads"

# Configurações de drivers
drivers:
  geckodriver:
    version: "latest"
    auto_download: true
  firefox:
    use_system: true
    profile: "default"

# Configurações do dashboard
dashboard:
  host: "127.0.0.1"
  port: 8050
  debug: true
  theme: "bootstrap"

# URLs de destino
urls:
  sam_login: "https://apps.itaipu.gov.br/SAM_SMA_Reports/SSAsExecuted.aspx"
  sam_reports: "https://apps.itaipu.gov.br/SAM_SMA_Reports/"

# Configurações de logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/scrap_sam.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# Configurações de dados
data:
  input_format: "excel"
  output_format: "excel"
  date_format: "%Y-%m-%d %H:%M:%S"
  encoding: "utf-8"

# Configurações de segurança
security:
  max_file_size: 100000000  # 100MB
  allowed_extensions: [".xlsx", ".xls", ".csv", ".json"]
  timeout_hard: 300  # 5 minutos

# Configurações de ambiente
environment:
  development: true
  test_mode: false
  mock_data: false
